name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Sync branches
      uses: TreTuna/sync-branches@v1
      with:
        # User token to be associated with this pull request.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Branch from make pull-request from
        FROM_BRANCH: master
        # Branch to make the pull-request against
        TO_BRANCH: readonly
